# -*- coding: utf-8 -*-
"""Projects CodewithFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_xe3xrhNdUQkTHh4bVSQrf9JRETq5F5

# **PDF Summarizer**
"""

# Install dependencies
!pip install -q pymupdf transformers sentencepiece accelerate

# Upload PDF
from google.colab import files

uploaded = files.upload()
pdf_file = list(uploaded.keys())[0]

# Extract text from PDF
import fitz

doc = fitz.open(pdf_file)

text = ""

for page in doc:
    text += page.get_text()

doc.close()

# Clean extracted text
text = text.replace("\n", " ")

# Load model and tokenizer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Tokenize input text - change words into numbers that the AI can process
inputs = tokenizer(
    text,
    return_tensors="pt",
    max_length=1024,
    truncation=True
)

# Generate summary - send the processed tokens to the AI model to create a summary
summary_ids = model.generate(
    inputs["input_ids"],
    max_length=150,
    min_length=50,
    num_beams=4,
    early_stopping=True
)

# Decode summary - change the AI’s numeric output back into readable sentences
summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

import textwrap

# Format summary into readable lines
formatted_summary = textwrap.fill(summary, width=80)

# Print summary
print("\n===== PDF SUMMARY =====\n")
print(formatted_summary)

